# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imapctl < Formula
  desc ""
  homepage "https://github.com/honest-magic/imapctl"
  version "0.0.3"

  on_macos do
    url "https://github.com/honest-magic/imapctl/releases/download/v0.0.3/imapctl_0.0.3_darwin_all.tar.gz"
    sha256 "4f86dfcbe1b4e11f690d4ed736c6f9fa830e54d87b4823fdff95ad8b12329788"

    def install
      bin.install "imapctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/honest-magic/imapctl/releases/download/v0.0.3/imapctl_0.0.3_linux_arm64.tar.gz"
      sha256 "59c015f545c1ed50196374e55646fddd70f6a6681bf4720e8c5f1e700b1fa21c"

      def install
        bin.install "imapctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/honest-magic/imapctl/releases/download/v0.0.3/imapctl_0.0.3_linux_amd64.tar.gz"
      sha256 "4d4b33784a88c7360ca0dbf715e155c13473a170bfc8d903d82dc3c6cf377a80"

      def install
        bin.install "imapctl"
      end
    end
  end
end
