# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imapctl < Formula
  desc ""
  homepage "https://github.com/honest-magic/imapctl"
  version "0.0.2"

  on_macos do
    url "https://github.com/honest-magic/imapctl/releases/download/v0.0.2/imapctl_0.0.2_darwin_all.tar.gz"
    sha256 "89c362f40109cc2f79e699e5790a3a68720c0aa7f2e8287ffb5b410789aaa9a0"

    def install
      bin.install "imapctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/honest-magic/imapctl/releases/download/v0.0.2/imapctl_0.0.2_linux_arm64.tar.gz"
      sha256 "2efc04203eb40e9bc5d72628af2885e0aeb3b4bf29e55480c65e7d49a8464a66"

      def install
        bin.install "imapctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/honest-magic/imapctl/releases/download/v0.0.2/imapctl_0.0.2_linux_amd64.tar.gz"
      sha256 "6e4835868cdec22ee755209a83058232f9c98c719cd6aa6e46e122e7c4c552db"

      def install
        bin.install "imapctl"
      end
    end
  end
end
