# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imapctl < Formula
  desc ""
  homepage "https://github.com/honest-magic/imapctl"
  version "0.0.3"

  on_macos do
    url "https://github.com/honest-magic/imapctl/releases/download/v0.0.3/imapctl_0.0.3_darwin_all.tar.gz"
    sha256 "a1775c90050107afc85549159e91149d7a2479b2312a12ce6c397ba8678b8116"

    def install
      bin.install "imapctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/honest-magic/imapctl/releases/download/v0.0.3/imapctl_0.0.3_linux_arm64.tar.gz"
      sha256 "a47a0e3c3fe2394e76dc5f03b92320b82cc182717bc95de4ab466a2ca1fd3db2"

      def install
        bin.install "imapctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/honest-magic/imapctl/releases/download/v0.0.3/imapctl_0.0.3_linux_amd64.tar.gz"
      sha256 "d8733869ab71620e18858065312d1ee56cd7336712c1fee753bc15df77a957cc"

      def install
        bin.install "imapctl"
      end
    end
  end
end
